const API='/api';let token=localStorage.getItem('harsh_library_token');let user=null;let mode='login';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch(API+path,{...opts,headers,...(opts.body?{body:JSON.stringify(opts.body)}:{})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Request failed');return d}
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;$('toast').appendChild(e);setTimeout(()=>e.remove(),3000)}
function setMode(next){mode=next;$('loginTab').classList.toggle('active',mode==='login');$('registerTab').classList.toggle('active',mode==='register');$('name').classList.toggle('hidden',mode!=='register');$('regRole').classList.toggle('hidden',mode!=='register');$('name').required=mode==='register';}
$('loginTab').onclick=()=>setMode('login');$('registerTab').onclick=()=>setMode('register');
$('authForm').onsubmit=async e=>{e.preventDefault();$('authMsg').textContent='';try{const body={email:$('email').value,password:$('password').value};if(mode==='register'){body.name=$('name').value;body.role=$('regRole').value}const d=await api(mode==='login'?'/auth/login':'/auth/register',{method:'POST',body});token=d.token;localStorage.setItem('harsh_library_token',token);user=d.user;enter();}catch(err){$('authMsg').textContent=err.message}};
async function enter(){if(!user)user=(await api('/auth/profile')).user;$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('session').classList.remove('hidden');$('who').textContent=user.name;$('role').textContent=user.role;$('adminTab').classList.toggle('hidden',user.role!=='librarian');loadBooks()}
$('logout').onclick=()=>{token=null;user=null;localStorage.removeItem('harsh_library_token');location.reload()};
async function loadBooks(){try{const q=$('search').value.trim();const d=await api(q?`/books/search?q=${encodeURIComponent(q)}`:'/books');$('books').innerHTML=d.books.map(b=>`<article class="book"><span class="tag">${esc(b.status)} · ${b.quantity} copies</span><h3>${esc(b.title)}</h3><p>by ${esc(b.author)}</p><p class="small">${esc(b.category)} · ISBN ${esc(b.isbn)}</p><div class="actions">${user.role==='student'?`<button ${b.quantity<1?'disabled':''} onclick="borrow('${b.bookId}')">Borrow</button>`:''}</div></article>`).join('')||'<p>No books found.</p>'}catch(e){toast(e.message)}}
async function borrow(id){try{await api(`/books/${id}/borrow`,{method:'POST'});toast('Book borrowed successfully.');loadBooks()}catch(e){toast(e.message)}}
async function loadLoans(){try{const d=await api('/transactions/my');$('loans').innerHTML=d.transactions.map(t=>`<div class="row"><div><strong>${esc(t.book?.title||'Unknown book')}</strong><div class="small">Borrowed ${new Date(t.borrowDate).toLocaleDateString()} · Due ${new Date(t.dueDate).toLocaleDateString()}</div></div><div><span>${esc(t.status)}</span>${t.status==='active'||t.status==='overdue'?` <button onclick="returnBook('${t.bookId}')">Return</button>`:''}</div></div>`).join('')||'<p>No lending history yet.</p>'}catch(e){toast(e.message)}}
async function returnBook(id){try{await api(`/books/${id}/return`,{method:'POST'});toast('Book returned.');loadLoans();loadBooks()}catch(e){toast(e.message)}}
async function loadAdmin(){try{const [t,u]=await Promise.all([api('/transactions'),api('/users')]);$('ledger').innerHTML=t.transactions.map(x=>`<div class="row"><div><strong>${esc(x.book?.title||'Unknown')}</strong><div class="small">${esc(x.user?.name||'Unknown')} · ${new Date(x.borrowDate).toLocaleDateString()}</div></div><span>${esc(x.status)}</span></div>`).join('')||'<p>No transactions.</p>';$('users').innerHTML=u.users.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><div class="small">${esc(x.email)}</div></div><span>${esc(x.role)}</span></div>`).join('')}catch(e){toast(e.message)}}
$('search').oninput=()=>loadBooks();$('refresh').onclick=loadBooks;$('bookForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const body=Object.fromEntries(f.entries());body.quantity=Number(body.quantity);try{await api('/books',{method:'POST',body});toast('Book added.');e.target.reset();loadAdmin()}catch(err){toast(err.message)}};
document.querySelectorAll('nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');['catalog','loans','admin'].forEach(v=>$(v+'View').classList.add('hidden'));$(btn.dataset.view+'View').classList.remove('hidden');if(btn.dataset.view==='catalog')loadBooks();if(btn.dataset.view==='loans')loadLoans();if(btn.dataset.view==='admin')loadAdmin()});
if(token)enter().catch(()=>{localStorage.removeItem('harsh_library_token');token=null});
