const ApiError = require('../utils/ApiError');
const { db, booksCollection, transactionsCollection } = require('../Config/firebase');
const books = require('../models/bookModel');
const tx = require('../models/transactionModel');
const users = require('../models/userModel');
const BORROW_DAYS = Number(process.env.BORROW_DURATION_DAYS || 14);

async function getBooks(req,res,next){try{const data=await books.findAllBooks(req.query);res.json({count:data.length,books:data});}catch(e){next(e)}}
async function searchBooks(req,res,next){try{const data=await books.searchBooks(req.query.q);res.json({count:data.length,books:data});}catch(e){next(e)}}
async function getBook(req,res,next){try{const book=await books.findBookById(req.params.id);if(!book)throw new ApiError(404,'Book not found.');res.json({book});}catch(e){next(e)}}
async function createBook(req,res,next){try{const quantity=req.body.quantity ?? 1;const book=await books.createBook({...req.body,quantity,status:quantity>0?'available':'borrowed'});res.status(201).json({message:'Book added successfully.',book});}catch(e){next(e)}}
async function updateBook(req,res,next){try{const current=await books.findBookById(req.params.id);if(!current)throw new ApiError(404,'Book not found.');const update={};['title','author','isbn','category'].forEach(k=>{if(req.body[k]!==undefined)update[k]=req.body[k]});if(req.body.quantity!==undefined){update.quantity=req.body.quantity;update.status=req.body.quantity>0?'available':'borrowed';}const book=await books.updateBook(req.params.id,update);res.json({message:'Book updated successfully.',book});}catch(e){next(e)}}
async function deleteBook(req,res,next){try{if(!await books.findBookById(req.params.id))throw new ApiError(404,'Book not found.');await books.deleteBook(req.params.id);res.json({message:'Book deleted successfully.'});}catch(e){next(e)}}
async function borrowBook(req,res,next){try{const bookId=req.params.id,userId=req.user.userId;let transactionId;await db.runTransaction(async t=>{const ref=booksCollection.doc(bookId);const snap=await t.get(ref);if(!snap.exists)throw new ApiError(404,'Book not found.');const book=snap.data();if(book.quantity<=0)throw new ApiError(400,'No copies are currently available.');const existing=await transactionsCollection.where('userId','==',userId).where('bookId','==',bookId).where('status','in',['active','overdue']).limit(1).get();if(!existing.empty)throw new ApiError(400,'You already have this book checked out.');const due=new Date(Date.now()+BORROW_DAYS*86400000);const newQty=book.quantity-1;const tr=transactionsCollection.doc();t.update(ref,{quantity:newQty,status:newQty?'available':'borrowed',updatedAt:new Date()});t.set(tr,{userId,bookId,type:'borrow',borrowDate:new Date(),returnDate:null,dueDate:due,status:'active',createdAt:new Date()});transactionId=tr.id;});const transaction=await tx.findTransactionById(transactionId);res.status(201).json({message:'Book borrowed successfully.',dueDate:transaction.dueDate,transaction});}catch(e){next(e)}}
async function returnBook(req,res,next){try{const active=await tx.findActiveBorrow(req.user.userId,req.params.id);if(!active)throw new ApiError(400,'No active loan exists for this book.');await db.runTransaction(async t=>{const bookRef=booksCollection.doc(req.params.id);const bookSnap=await t.get(bookRef);if(!bookSnap.exists)throw new ApiError(404,'Book not found.');const book=bookSnap.data();t.update(bookRef,{quantity:book.quantity+1,status:'available',updatedAt:new Date()});t.update(transactionsCollection.doc(active.transactionId),{type:'return',returnDate:new Date(),status:'returned',updatedAt:new Date()});});res.json({message:'Book returned successfully.',transaction:await tx.findTransactionById(active.transactionId)});}catch(e){next(e)}}
async function enrich(t){const [u,b]=await Promise.all([users.findUserById(t.userId),books.findBookById(t.bookId)]);return {...t,user:u?{userId:u.userId,name:u.name,email:u.email}:null,book:b?{bookId:b.bookId,title:b.title,author:b.author}:null}}
async function allTransactions(req,res,next){try{await tx.markOverdueTransactions();const list=await tx.findAllTransactions();res.json({count:list.length,transactions:await Promise.all(list.map(enrich))});}catch(e){next(e)}}
async function myTransactions(req,res,next){try{await tx.markOverdueTransactions();const list=await tx.findTransactionsByUser(req.user.userId);res.json({count:list.length,transactions:await Promise.all(list.map(enrich))});}catch(e){next(e)}}
module.exports={getBooks,searchBooks,getBook,createBook,updateBook,deleteBook,borrowBook,returnBook,allTransactions,myTransactions};
